; PlatformIO Project Configuration File

[env:ESP32_Without_LoRa]  
platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.04/platform-espressif32.zip
board = esp32dev
framework = arduino
upload_speed = 921600
monitor_speed = 115200
lib_deps = 
	jgromes/RadioLib@^7.4.0
	esp32async/ESPAsyncWebServer@^3.8.0
	bblanchon/ArduinoJson@^7.4.2
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
build_flags =
    -DPIO_ENV_NAME=\"${PIOENV}\"
	-DESP32_WITHOUT_LORA
	-DCORE_DEBUG_LEVEL=0
    -DLOG_LOCAL_LEVEL=ESP_LOG_NONE

[env:LILYGO_T3_LoRa32_V1_6_1]  ;https://lilygo.cc/products/lora3?_pos=1&_sid=2b08416ed&_ss=r&variant=42272562282677
platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.04/platform-espressif32.zip
board = esp32dev
framework = arduino
upload_speed = 921600
monitor_speed = 115200
lib_deps = 
	jgromes/RadioLib@^7.4.0
	esp32async/ESPAsyncWebServer@^3.8.0
	bblanchon/ArduinoJson@^7.4.2
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
build_flags =
    -DPIO_ENV_NAME=\"${PIOENV}\"
	-DLILYGO_T3_LORA32_V1_6_1
	-DCORE_DEBUG_LEVEL=0
    -DLOG_LOCAL_LEVEL=ESP_LOG_NONE

[env:LILYGO_T-Beam]  ;https://lilygo.cc/products/t-beam
platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.04/platform-espressif32.zip
board = esp32dev
framework = arduino
upload_speed = 921600
monitor_speed = 115200
lib_deps = 
	jgromes/RadioLib@^7.4.0
	esp32async/ESPAsyncWebServer@^3.8.0
	bblanchon/ArduinoJson@^7.4.2
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
build_flags =
    -DPIO_ENV_NAME=\"${PIOENV}\"
    -DLILYGO_T_BEAM
	-DCORE_DEBUG_LEVEL=0
    -DLOG_LOCAL_LEVEL=ESP_LOG_NONE


[env:HELTEC_Wireless_Stick_Lite_V3]  ;https://heltec.org/project/wireless-stick-lite-v2/
platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.04/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
upload_speed = 921600
monitor_speed = 115200
lib_deps = 
	jgromes/RadioLib@^7.4.0
	esp32async/ESPAsyncWebServer@^3.8.0
	bblanchon/ArduinoJson@^7.4.2
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
build_flags =
    -DPIO_ENV_NAME=\"${PIOENV}\"
    -DHELTEC_WIRELESS_STICK_LITE_V3
	-DCORE_DEBUG_LEVEL=0
    -DLOG_LOCAL_LEVEL=ESP_LOG_NONE
upload_port = COM13  ; Hier den Port erzwingen 



[env:HELTEC_WiFi_LoRa_32_V3]  ;https://heltec.org/project/wifi-lora-32-v3
platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.04/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
upload_speed = 921600
monitor_speed = 115200
lib_deps = 
	jgromes/RadioLib@^7.4.0
	esp32async/ESPAsyncWebServer@^3.8.0
	bblanchon/ArduinoJson@^7.4.2
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
build_flags =
    -DPIO_ENV_NAME=\"${PIOENV}\"
    -DHELTEC_WIFI_LORA_32_V3
	-DCORE_DEBUG_LEVEL=0
    -DLOG_LOCAL_LEVEL=ESP_LOG_NONE




[env:HELTEC_WiFi_LoRa_32_V4]  ;https://heltec.org/project/wifi-lora-32-v4/
platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.04/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
upload_speed = 921600
monitor_speed = 115200
lib_deps = 
	jgromes/RadioLib@^7.4.0
	esp32async/ESPAsyncWebServer@^3.8.0
	bblanchon/ArduinoJson@^7.4.2
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
build_flags =
    -DPIO_ENV_NAME=\"${PIOENV}\"
    -DHELTEC_WIFI_LORA_32_V4
	-DCORE_DEBUG_LEVEL=0
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DLOG_LOCAL_LEVEL=ESP_LOG_NONE


